
-- Pregunta 1
-- (Solución de la pregunta 1)
SELECT V.VUELO_ID, TO_CHAR(V.FECHA_HORA_PARTIDA, 'DD/MM/YYYY') AS FECHA_HORA_PARTIDA,
       TO_CHAR(V.FECHA_HORA_LLEGADA, 'DD/MM/YYYY') AS FECHA_HORA_LLEGADA,
       V.AEROPUERTO_PARTIDA_ID, V.AEROPUERTO_LLEGADA_ID, A.NRO_PLACA, A.MODELO
FROM AP_VUELOS V, AP_AVIONES A
WHERE V.AVION_ID = A.AVION_ID AND A.MODELO like 'Boeing 737 MAX%';



-- Pregunta 2
-- (Solución de la pregunta 2)
SELECT V.VUELO_ID, TO_CHAR(V.FECHA_HORA_PARTIDA, 'DD/MM/YYYY') AS FECHA_HORA_PARTIDA,
       TO_CHAR(V.FECHA_HORA_LLEGADA, 'DD/MM/YYYY') AS FECHA_HORA_LLEGADA, P.TIPO_DOCUMENTO,
       P.NOMBRES, P.AP_PATERNO, P.AP_MATERNO, P.FECHA_NACIMIENTO, P.SEXO, P.CELULAR,
       P.EMAIL, V.AEROPUERTO_PARTIDA_ID, V.AEROPUERTO_LLEGADA_ID
FROM AP_VUELOS V, AP_BOLETOS B, AP_PASAJEROS P
WHERE V.VUELO_ID = B.VUELO_ID AND B.PASAJERO_ID = P.PASAJERO_ID AND
      P.NOMBRES like 'Clara' AND P.AP_PATERNO like 'Rojo'
      AND P.AP_MATERNO = 'Campos';



-- Pregunta 3
-- (Solución de la pregunta 3)
SELECT P.TIPO_DOCUMENTO, P.NRO_DOCUMENTO, P.NOMBRES, P.AP_PATERNO,
       P.AP_MATERNO, P.FECHA_NACIMIENTO, P.SEXO, P.CELULAR, P.EMAIL
FROM AP_PASAJEROS P
WHERE extract(year from sysdate) - extract(year from P.FECHA_NACIMIENTO) < 18;



-- Pregunta 4
-- (Solución de la pregunta 4)
SELECT A.AVION_ID, A.MODELO,
       TO_CHAR(M.FECHA_FIN_EST, 'DD/MM/YYYY') AS FECHA_FIN_EST,
       ROUND(MONTHS_BETWEEN(SYSDATE, (m.fecha_fin_est)), 2) AS CANTIDAD_MESES
FROM AP_AVIONES A, AP_MANT_AVIONES M
WHERE A.AVION_ID = M.AVION_ID AND A.MODELO LIKE 'Airbus%';



-- Pregunta 5
-- (Solución de la pregunta 5)
SELECT (P.NOMBRES || ' ' || P.AP_PATERNO || ' ' || P.AP_MATERNO) AS NOMBRE_COMPLETO,
       B.BOLETO_ID, B.NRO_SERIE, B.CORRELATIVO,
       TO_CHAR(B.FECHA_EMISION, 'DD/MM/YYYY') AS FECHA_EMISION
FROM AP_PASAJEROS P, AP_BOLETOS B
WHERE P.PASAJERO_ID = B.PASAJERO_ID AND
      P.PASAJERO_ID IN (
      -- Esta subconsulta selecciona todos los "PARIENTE_ID" (familiares) del pasajero
      -- Jorge Chávez Portocarrero buscando en la tabla "AP_PARENTESCOS".
      SELECT PA.PARIENTE_ID
      FROM AP_PARENTESCOS PA, AP_PASAJEROS PS
      WHERE PA.PASAJERO_ID = PS.PASAJERO_ID AND
            PS.NOMBRES = 'Jorge' AND PS.AP_PATERNO = 'Ch¿vez' AND PS.AP_MATERNO = 'Portocarrero'
);



-- Pregunta 6
-- (Solución de la pregunta 6)
INSERT INTO AP_VUELOS
(VUELO_ID, FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, AVION_ID, AEROPUERTO_PARTIDA_ID, AEROPUERTO_LLEGADA_ID)
VALUES ('VM4001', TO_DATE('2025-05-20 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-05-20 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 105, 1, 6);


INSERT INTO AP_VUELOS
(VUELO_ID, FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, AVION_ID, AEROPUERTO_PARTIDA_ID, AEROPUERTO_LLEGADA_ID)
VALUES ('XY0402', TO_DATE('2025-05-21 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-05-21 17:45:00', 'YYYY-MM-DD HH24:MI:SS'), 104, 2, 3);


INSERT INTO AP_VUELOS
(VUELO_ID, FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, AVION_ID, AEROPUERTO_PARTIDA_ID, AEROPUERTO_LLEGADA_ID)
VALUES ('ZK0083', TO_DATE('2025-05-22 06:15:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-05-22 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 112, 3, 10);


COMMIT; -- Guardar los cambios.



-- Pregunta 7
-- (Solución de la pregunta 7)
DELETE FROM AP_PASAJEROS
WHERE TIPO_DOCUMENTO = 'P' AND NRO_DOCUMENTO = 'USA654321';



-- Pregunta 8
-- (Solución de la pregunta 8)
UPDATE AP_EMPLEADOS
SET EMAIL = 'carlos.ruiz@example.com'
WHERE NOMBRES = 'Carlos' AND AP_PATERNO = 'Ruiz' AND AP_MATERNO = 'D¿az';



-- Pregunta 9
-- (Solución de la pregunta 9)
UPDATE AP_EMPLEADOS
SET SALARIO = SALARIO + SALARIO*0.15
WHERE CARGO_ID IN (
      SELECT CARGO_ID
      FROM AP_CARGOS
      WHERE DETALLE_CARGO = 'Piloto'
);



-- Pregunta 10
-- (Solución de la pregunta 10)
SELECT UPPER((AP_PATERNO || ' ' || AP_MATERNO || ', ' || NOMBRES)) AS NOMBRE_COMPLETO,
       FECHA_INGRESO
FROM AP_EMPLEADOS
WHERE extract(year from FECHA_INGRESO) = 2024 AND ACTIVO = 1
ORDER BY FECHA_INGRESO;

