
--PREGUNTA 1
--(Solución de la pregunta 1)
CREATE TABLE CITAS_MEDICAS (
    CITA_ID NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    PERSONAL_ID NUMBER NOT NULL,
    FECHA_CITA DATE NOT NULL,
    HORA_CITA DATE NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'Programada',
    CONSTRAINT PK_CITA_ID PRIMARY KEY (CITA_ID)
);




--PREGUNTA 2
--(Solución de la pregunta 2)
CREATE TABLE RESULTADOS_LABORATORIO(
    RESULTADO_ID NUMBER NOT NULL,
    ATENCION_ID NUMBER NOT NULL,
    TIPO_PRUEBA VARCHAR2(100) NOT NULL,
    FECHA_RESULTADO DATE NOT NULL,
    VALOR_RESULTADO VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_RESULTADO_ID PRIMARY KEY (RESULTADO_ID)
);




--PREGUNTA 3
--(Solución de la pregunta 3)
COMMENT ON COLUMN BOLETAS.BOLETA_ID IS 'Identificador único de la boleta de pago.';
COMMENT ON COLUMN BOLETAS.PACIENTE_ID IS 'Paciente asociado a la boleta.';
COMMENT ON COLUMN BOLETAS.FECHA_EMISION IS 'Fecha en que se emitió la boleta';
COMMENT ON COLUMN BOLETAS.MONTO_TOTAL IS 'Monto total facturado.';
COMMENT ON COLUMN BOLETAS.METODO_PAGO IS 'Método de pago utilizado (efectivo, tarjeta, etc).';
COMMENT ON COLUMN BOLETAS.NRO_SERIE IS 'Número de serie de la boleta.';




--PREGUNTA 4
--(Solución de la pregunta 4)
CREATE TABLE INVENTARIO_MEDICAMENTOS (
    INVENTARIO_ID NUMBER NOT NULL,
    MEDICAMENTO_ID NUMBER NOT NULL,
    UBICACION VARCHAR2(100) NOT NULL,
    CANTIDAD NUMBER,
    CONSTRAINT PK_INVENTARIO_ID PRIMARY KEY (INVENTARIO_ID)
);




--PREGUNTA 5
--(Solución de la pregunta 5)
ALTER TABLE INVENTARIO_MEDICAMENTOS ADD CONSTRAINT FK_MEDICAMENTO_ID FOREIGN KEY (MEDICAMENTO_ID) references MEDICAMENTOS (MEDICAMENTO_ID);




--PREGUNTA 6
--(Solución de la pregunta 6)
ALTER TABLE PACIENTES RENAME COLUMN APELLIDOS TO PRIMER_APELLIDO; -- Modificar la columna "APELLIDOS" a "PRIMER_APELLIDO".
ALTER TABLE PACIENTES MODIFY PRIMER_APELLIDO VARCHAR2(50); -- Modificar "PRIMER_APELLIDO" a 50 caracteres como máximo.
ALTER TABLE PACIENTES ADD SEGUNDO_APELLIDO VARCHAR2(50) NOT NULL; -- Crear la columna "SEGUNDO_APELLIDO".




--PREGUNTA 7
--(Solución de la pregunta 7)
ALTER TABLE CITAS_MEDICAS ADD CONSTRAINT FK_PACIENTE_ID FOREIGN KEY (PACIENTE_ID) references PACIENTES (PACIENTE_ID);
ALTER TABLE CITAS_MEDICAS ADD CONSTRAINT FK_PERSONAL_ID FOREIGN KEY (PERSONAL_ID) references PERSONALES_MEDICOS (PERSONAL_ID);




--PREGUNTA 8
--(Solución de la pregunta 8)
ALTER TABLE RESULTADOS_LABORATORIO ADD CONSTRAINT FK_ATENCION_ID FOREIGN KEY (ATENCION_ID) references ATENCIONES_MEDICAS (ATENCION_ID);




--PREGUNTA 9
--(Solución de la pregunta 9)
ALTER TABLE PACIENTES ADD CONSTRAINT CH_SEXO CHECK (SEXO='M' or SEXO='F');




--PREGUNTA 10
--(Solución de la pregunta 10)
ALTER TABLE RECETAS_MEDICAMENTOS ADD CONSTRAINT CH_CANTIDAD_DOSIS CHECK (CANTIDAD_DOSIS > 0);
ALTER TABLE BOLETAS ADD CONSTRAINT CH_MONTO_TOTAL CHECK (MONTO_TOTAL > 0);




--PREGUNTA 11
--(Solución de la pregunta 11)
ALTER TABLE PACIENTES MODIFY NRO_DOCUMENTO VARCHAR2(15);
ALTER TABLE PACIENTES MODIFY NOMBRE VARCHAR2(80);




--PREGUNTA 12
--(Solución de la pregunta 12)
ALTER TABLE MEDICAMENTOS ADD LOTE VARCHAR2(50);
COMMENT ON COLUMN MEDICAMENTOS.LOTE IS 'Identificador del lote de fabricación';

ALTER TABLE MEDICAMENTOS ADD FECHA_VENCIMIENTO DATE;
COMMENT ON COLUMN MEDICAMENTOS.FECHA_VENCIMIENTO IS 'Fecha límite de uso del medicamento';

ALTER TABLE MEDICAMENTOS ADD PRESENTACION VARCHAR2(50);
COMMENT ON COLUMN MEDICAMENTOS.PRESENTACION IS 'Formato físico del medicamento';




--PREGUNTA 13
--(Solución de la pregunta 13)
ALTER TABLE PACIENTES ADD USUARIO_CREACION NUMBER;
COMMENT ON COLUMN PACIENTES.USUARIO_CREACION IS 'Identificador del usuario que creó el registro.';

ALTER TABLE PACIENTES ADD FECHA_CREACION DATE;
COMMENT ON COLUMN PACIENTES.FECHA_CREACION IS 'Fecha en que se creó el registro.';

ALTER TABLE PACIENTES ADD USUARIO_ULT_MODIF NUMBER;
COMMENT ON COLUMN PACIENTES.USUARIO_ULT_MODIF
IS 'Identificador del usuario que modificó por última vez el registro.';

ALTER TABLE PACIENTES ADD FECHA_ULT_MODIF DATE;
COMMENT ON COLUMN PACIENTES.FECHA_ULT_MODIF IS 'Fecha de la última modificación del registro.';















