
-- PREGUNTA 1
--(Solución de la pregunta 1)
CREATE TABLE AP_EMPLEADOS (
    EMPLEADO_ID  CHAR(6 BYTE)  NOT NULL,
    TIPO_DOCUMENTO  CHAR(1 BYTE ) NOT NULL,
    NRO_DOCUMENTO  VARCHAR2(12 BYTE) NOT NULL,
    NOMBRES  VARCHAR2(30 BYTE) NOT NULL,
    AP_PATERNO  VARCHAR2(30 BYTE)  NOT NULL,
    AP_MATERNO  VARCHAR2(30 BYTE)  NOT NULL,
    FECHA_NACIMIENTO DATE  NOT NULL,
    SEXO  CHAR(1 BYTE)  NOT NULL,
    CELULAR  CHAR(9 BYTE),
    EMAIL  VARCHAR2(30 BYTE) NOT NULL,
    CARGO_ID NUMBER NOT NULL,
    CONSTRAINT PK_EMPLEADO_ID PRIMARY KEY (EMPLEADO_ID),
    CONSTRAINT FK_CARGO_ID FOREIGN KEY (CARGO_ID) references AP_CARGOS (CARGO_ID)
);


-- PREGUNTA 2
--(Solución de la pregunta 2)
COMMENT ON COLUMN AP_EMPLEADOS.EMPLEADO_ID IS 'Código identificador del empleado';

COMMENT ON COLUMN AP_EMPLEADOS.TIPO_DOCUMENTO IS
'Tipo de documento del empleado puede ser D: DNI o C: Carnet de extranjería';

COMMENT ON COLUMN AP_EMPLEADOS.NRO_DOCUMENTO IS
'Número de documento del empleado puede tener 8 caracteres si es DNI o 12 si es Carnet de extranjería';

COMMENT ON COLUMN AP_EMPLEADOS.NOMBRES IS 'Nombres del empleado';


-- PREGUNTA 3
--(Solución de la pregunta 3)
ALTER TABLE AP_EMPLEADOS
ADD (
    FECHA_INGRESO DATE DEFAULT SYSDATE NOT NULL,
    SALARIO NUMBER(7,2) CONSTRAINT ch_salario CHECK (SALARIO >= 1130 AND  SALARIO < 10000) NOT NULL,
    ACTIVO NUMBER DEFAULT 1 NOT NULL
);


-- PREGUNTA 4
--(Solución de la pregunta 4)
ALTER TABLE AP_EMPLEADOS_VUELOS
ADD CONSTRAINT FK_EMPLEADO_ID FOREIGN KEY (EMPLEADO_ID) references AP_EMPLEADOS (EMPLEADO_ID);


-- PREGUNTA 5
--(Solución de la pregunta 5)
ALTER TABLE AP_PASAJEROS
MODIFY(
    EMAIL VARCHAR2(50),
    CELULAR CHAR(15),
    NOMBRES VARCHAR2(50)
);


-- PREGUNTA 6
--(Solución de la pregunta 6)
ALTER TABLE AP_CIUDADES RENAME COLUMN NOMBRE TO NOMBRE_CIUDAD;
ALTER TABLE AP_CARGOS RENAME COLUMN DESCRIPCION TO DETALLE_CARGO;


-- PREGUNTA 7
--(Solución de la pregunta 7)
ALTER TABLE AP_PARENTESCOS DROP COLUMN VINCULO;


-- PREGUNTA 8
--(Solución de la pregunta 8)
DROP TABLE AP_PARENTESCOS CASCADE CONSTRAINTS;







