//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="ServiciosWeb.CalculadoraWS")]
    public interface CalculadoraWS
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiciosWeb.multiplicarResponse multiplicar(ServiciosWeb.multiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/multiplicarResponse")]
        System.Threading.Tasks.Task<ServiciosWeb.multiplicarResponse> multiplicarAsync(ServiciosWeb.multiplicarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiciosWeb.sumarResponse sumar(ServiciosWeb.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/sumarResponse")]
        System.Threading.Tasks.Task<ServiciosWeb.sumarResponse> sumarAsync(ServiciosWeb.sumarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiciosWeb.restarResponse restar(ServiciosWeb.restarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/restarResponse")]
        System.Threading.Tasks.Task<ServiciosWeb.restarResponse> restarAsync(ServiciosWeb.restarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softprog.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/dividirRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/dividirResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiciosWeb.dividirResponse dividir(ServiciosWeb.dividirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CalculadoraWS/dividirRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CalculadoraWS/dividirResponse")]
        System.Threading.Tasks.Task<ServiciosWeb.dividirResponse> dividirAsync(ServiciosWeb.dividirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class multiplicarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double numero1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double numero2;
        
        public multiplicarRequest()
        {
        }
        
        public multiplicarRequest(double numero1, double numero2)
        {
            this.numero1 = numero1;
            this.numero2 = numero2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class multiplicarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multiplicarResponse()
        {
        }
        
        public multiplicarResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class sumarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double numero1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double numero2;
        
        public sumarRequest()
        {
        }
        
        public sumarRequest(double numero1, double numero2)
        {
            this.numero1 = numero1;
            this.numero2 = numero2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class sumarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sumarResponse()
        {
        }
        
        public sumarResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restar", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class restarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double numero1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double numero2;
        
        public restarRequest()
        {
        }
        
        public restarRequest(double numero1, double numero2)
        {
            this.numero1 = numero1;
            this.numero2 = numero2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restarResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class restarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public restarResponse()
        {
        }
        
        public restarResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dividir", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class dividirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double numero1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double numero2;
        
        public dividirRequest()
        {
        }
        
        public dividirRequest(double numero1, double numero2)
        {
            this.numero1 = numero1;
            this.numero2 = numero2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dividirResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class dividirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public dividirResponse()
        {
        }
        
        public dividirResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CalculadoraWSChannel : ServiciosWeb.CalculadoraWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CalculadoraWSClient : System.ServiceModel.ClientBase<ServiciosWeb.CalculadoraWS>, ServiciosWeb.CalculadoraWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalculadoraWSClient() : 
                base(CalculadoraWSClient.GetDefaultBinding(), CalculadoraWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CalculadoraWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraWSClient(EndpointConfiguration endpointConfiguration) : 
                base(CalculadoraWSClient.GetBindingForEndpoint(endpointConfiguration), CalculadoraWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalculadoraWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalculadoraWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.multiplicarResponse ServiciosWeb.CalculadoraWS.multiplicar(ServiciosWeb.multiplicarRequest request)
        {
            return base.Channel.multiplicar(request);
        }
        
        public double multiplicar(double numero1, double numero2)
        {
            ServiciosWeb.multiplicarRequest inValue = new ServiciosWeb.multiplicarRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            ServiciosWeb.multiplicarResponse retVal = ((ServiciosWeb.CalculadoraWS)(this)).multiplicar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.multiplicarResponse> ServiciosWeb.CalculadoraWS.multiplicarAsync(ServiciosWeb.multiplicarRequest request)
        {
            return base.Channel.multiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.multiplicarResponse> multiplicarAsync(double numero1, double numero2)
        {
            ServiciosWeb.multiplicarRequest inValue = new ServiciosWeb.multiplicarRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            return ((ServiciosWeb.CalculadoraWS)(this)).multiplicarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.sumarResponse ServiciosWeb.CalculadoraWS.sumar(ServiciosWeb.sumarRequest request)
        {
            return base.Channel.sumar(request);
        }
        
        public double sumar(double numero1, double numero2)
        {
            ServiciosWeb.sumarRequest inValue = new ServiciosWeb.sumarRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            ServiciosWeb.sumarResponse retVal = ((ServiciosWeb.CalculadoraWS)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.sumarResponse> ServiciosWeb.CalculadoraWS.sumarAsync(ServiciosWeb.sumarRequest request)
        {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.sumarResponse> sumarAsync(double numero1, double numero2)
        {
            ServiciosWeb.sumarRequest inValue = new ServiciosWeb.sumarRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            return ((ServiciosWeb.CalculadoraWS)(this)).sumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.restarResponse ServiciosWeb.CalculadoraWS.restar(ServiciosWeb.restarRequest request)
        {
            return base.Channel.restar(request);
        }
        
        public double restar(double numero1, double numero2)
        {
            ServiciosWeb.restarRequest inValue = new ServiciosWeb.restarRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            ServiciosWeb.restarResponse retVal = ((ServiciosWeb.CalculadoraWS)(this)).restar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.restarResponse> ServiciosWeb.CalculadoraWS.restarAsync(ServiciosWeb.restarRequest request)
        {
            return base.Channel.restarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.restarResponse> restarAsync(double numero1, double numero2)
        {
            ServiciosWeb.restarRequest inValue = new ServiciosWeb.restarRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            return ((ServiciosWeb.CalculadoraWS)(this)).restarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.dividirResponse ServiciosWeb.CalculadoraWS.dividir(ServiciosWeb.dividirRequest request)
        {
            return base.Channel.dividir(request);
        }
        
        public double dividir(double numero1, double numero2)
        {
            ServiciosWeb.dividirRequest inValue = new ServiciosWeb.dividirRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            ServiciosWeb.dividirResponse retVal = ((ServiciosWeb.CalculadoraWS)(this)).dividir(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.dividirResponse> ServiciosWeb.CalculadoraWS.dividirAsync(ServiciosWeb.dividirRequest request)
        {
            return base.Channel.dividirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.dividirResponse> dividirAsync(double numero1, double numero2)
        {
            ServiciosWeb.dividirRequest inValue = new ServiciosWeb.dividirRequest();
            inValue.numero1 = numero1;
            inValue.numero2 = numero2;
            return ((ServiciosWeb.CalculadoraWS)(this)).dividirAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalculadoraWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalculadoraWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/SoftProg-1.0-SNAPSHOT/CalculadoraWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalculadoraWSClient.GetBindingForEndpoint(EndpointConfiguration.CalculadoraWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalculadoraWSClient.GetEndpointAddress(EndpointConfiguration.CalculadoraWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CalculadoraWSPort,
        }
    }
}
